Opgave 3.1. Lad

$$
s=2, \quad t=3, \quad A=\left[\begin{array}{ccc}
2 & 1 & -1 \\
0 & 2 & 5
\end{array}\right], \quad B=\left[\begin{array}{ccc}
1 & -1 & 0 \\
0 & 1 & -1
\end{array}\right] .
$$


Hvilke af de følgende udtryk er tilladt? For dem, der er tilladt, beregn svaret (python kan godt bruges); for dem, der er ikke tilladt, forklar hvorfor.


(a) $s B$, (b) $A+t B$, (c) $A^T$, (d) $A^T+s B$, (e) $s A^T-t B^T$,


(f) $A B$, (g) $B A$, (h) $A^T B$, (i) $s A B^T$, (j) $B A^T B t$.


In [1]:
import numpy as np
import matplotlib.pyplot as plt

s = 2
t = 3
A = np.array([[2,1,-1],[0,2,5]])
B = np.array([[1,-1,0],[0,1,-1]])
print("A er korrekt og kan regnes til:\n",s*B)
print("B er korrekt og giver:\n", A+(t*B))
print("C er korrekt og giver\n", A.T)
print("D er ikke mulig")
print("E mulig og giver os:\n",s*A.T-(t*B.T))
print("F er ikke mulig")
print("G er ikke mulig")
print("H er mulig og giver:\n",A.T@B)
print("I er mulig og giver:\n",(s*A)@B.T)
print("J er mulig og giver: \n",((B@A.T)@B)*t)

A er korrekt og kan regnes til:
 [[ 2 -2  0]
 [ 0  2 -2]]
B er korrekt og giver:
 [[ 5 -2 -1]
 [ 0  5  2]]
C er korrekt og giver
 [[ 2  0]
 [ 1  2]
 [-1  5]]
D er ikke mulig
E mulig og giver os:
 [[ 1  0]
 [ 5  1]
 [-2 13]]
F er ikke mulig
G er ikke mulig
H er mulig og giver:
 [[ 2 -2  0]
 [ 1  1 -2]
 [-1  6 -5]]
I er mulig og giver:
 [[ 2  4]
 [-4 -6]]
J er mulig og giver: 
 [[  3  -9   6]
 [  6 -15   9]]


Opgave 3.2. Lad $R_0$ og $R_1$ være rotationsmatricerne fra eksempel 4.8 i Notesæt 4 , taget med $c=0,8, s=0,6$. Beregn matrixprodukterne

$$
R_0 R_1 \quad \text { og } \quad R_1 R_0
$$

og bekræft at resultaterne er forskellige. Hvad betyder dette for en opgraderet version af robotarmen fra Afleveringsopgave 1 hvor ledende kan bøje sig i tre dimensioner?

In [2]:
c = 0.8
s = 0.6

R0 = np.array([[1,0,0],
               [0,c,-s],
               [0,s,c]])

R1 = np.array([[c,0,-s],
               [0,1,0],
               [s,0,c]])

print("R0R1:\n",R0@R1)
print("R1R0:\n",R1@R0)
print("Dette betyder at det generelt ikke er ligegyldigt \n hvilken rotation vi laver  pa led d")

R0R1:
 [[ 0.8   0.   -0.6 ]
 [-0.36  0.8  -0.48]
 [ 0.48  0.6   0.64]]
R1R0:
 [[ 0.8  -0.36 -0.48]
 [ 0.    0.8  -0.6 ]
 [ 0.6   0.48  0.64]]
Dette betyder at det generelt ikke er ligegyldigt 
 hvilken rotation vi laver  pa led d


Opgave 3.3. 11 computere 

$C_0, \ldots, C_{10}$ 

er forbundet i netværket som nedenfor


(a) Dan i python nabomatricen 

$A=\left(a_{i j}\right) \in \mathbb{R}^{11 \times 11}$, som har $a_{i j}=1$ hvis $C_i$ er direkte forbundet til $C_j$ og har $a_{i j}=0$ ellers. Bemærk $C_i$ er ikke forbundet til sig selv. Det kan hjælpe at bruge np.zeros (...) og operationer som $\mathrm{a}[0,[1,3]]=1$.

(b) Tjek at $A^T=A$.

Lad $A^k$ være matrixproduktet af $A$ med sig selv $k$-gange:
$$
A^k=\underbrace{A A \ldots A}_k .
$$

Beregn $A^2=A, A^3$ og $A^5$ i python. Det vides at den $(i, j)$-indgang i $A^k$ kan betragtes som antallet af stier af længde $k$ i netværket fra $C_i$ til $C_j$. Brug dette og de beregnede matricer til at svare på følgende spørgsmål, der kan eventuelt bruges funktionerne $\mathrm{np}$.count_nonzero og $\mathrm{np}$. argwhere:

(c) Hvor mange computer har en sti af længde 2 til $C_5$ ?

(d) Hvor mange computer har en sti af længde 2 til $C_7$ ?

(e) Hvilke computer kan ikke nås fra $C_9$ med en sti af længde højst 3?

(f) Er der nogle computer, som ikke kan nås fra $C_0$ med en sti af længde 4?
Kan du forklare hvorfor $A^k$ tæller stier af længde $k$ på denne måde?

In [3]:
#Opgave a
n = np.array([[0,1,0,1,0,0,0,0,0,0,0],
              [1,0,1,1,0,0,0,0,0,0,0],
              [0,1,0,1,1,1,0,0,0,0,0],
              [1,1,1,0,0,0,1,0,0,0,0],
              [0,0,1,0,0,1,0,0,0,0,1],
              [0,0,1,0,1,0,1,0,1,1,1],
              [0,0,0,1,0,1,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0,0],
              [0,0,0,0,0,1,0,1,0,1,0],
              [0,0,0,0,0,1,0,0,1,0,1],
              [0,0,0,0,1,1,0,0,0,1,0],])

#Opgave b
print("Opgave B\n")
print("A == A.T", np.array_equal(n,n.T))

#Opgave c
print("Opgave C\n")
A2 = n@n
greaterThan1 = A2>0
print("The coloumn representing C5\n", greaterThan1[:,6])
print("Number of computers:", np.count_nonzero(greaterThan1[:,6]==True))
print("Roads must be equal to 2, therefore some can reach on 1 but not on 2\n")

#Opgave d
print("Opgave D\n")
print("The coloumn representing C7\n", greaterThan1[:,8])
print("Number of compouters:",np.count_nonzero(greaterThan1[:,8]==True))

#opgave E
print("Opgave E\n")
A3 = n@n@n
greaterThan2 = A3>0

reachC9 = [True,True,True,True,True,True,True,True,True,True,True]
for x in range(0,10):
    reachC9[x] = (n[x,10]>0) or (A2[x,10]>0) or (A3[x,10]>0)
    
print("The list representing if Ci can reach C9 in 3 or less",reachC9)
print("Number of Computers that are not able to do so",reachC9.count(False))
print("")

#opgave F
print("Opgave F\n")
A4 = n@n@n@n
greaterThan4 = A4>0
print("Row representing C0\n",greaterThan4[0,:])
print("Derved kan 7 ikke nås")


Opgave B

A == A.T True
Opgave C

The coloumn representing C5
 [ True  True  True False  True False  True False  True  True  True]
Number of computers: 8
Roads must be equal to 2, therefore some can reach on 1 but not on 2

Opgave D

The coloumn representing C7
 [False False  True False  True  True  True False  True  True  True]
Number of compouters: 7
Opgave E

The list representing if Ci can reach C9 in 3 or less [False, True, True, True, True, True, True, True, True, True, True]
Number of Computers that are not able to do so 1

Opgave F

Row representing C0
 [ True  True  True  True  True  True  True False  True  True  True]
Derved kan 7 ikke nås


## Opgave 3.4.
Betragt algoritmen MatrixProdukt(A,B) fra notesæt 5, 5.1. for matrixproduktet af
A $\in \mathbb{R}^{mxn},B \in \mathbb{R}^{nxr}$.
Vi kan skrive række-søjleproduktet ud og flytte nulstilling af resultatmatricen C til begyndelsen for at få følgende:

                                                                                                

Matrixprodukt-II(A,B)

C = 0 mxr

for i $\in {0-m-1}$:

    for j$\in {0-r-1}$:
    
        for k $\in {0-n-1}$:
        
            $c_{ij} = c_{ij} + a_{ik} * b_{kj}
return C


Dette har den fordel, at linjer 2, 3, 4 kan nu ombyttes, som vi har lyst.
På denne måde får vi i alt 6 forskellige algoritmer. 
Tre af disse algoritmer svarer til de tre forskellige præsentationer af matrixproduktet i Notesæt 4, ligninger (4.1) , (4.2) og (4.3) :
hvilke tre? 
Kan du give tilsvarende fortolkninger for nogle af de resterende tre algoritmer?