# Opgave 4.1.
Lad $A \in \mathbb{R}^{1000 \times 70}, B, C \in \mathbb{R}^{70 \times 3000}, D \in \mathbb{R}^{3000 \times 1000}$. Angiv antallet af flops for de følgende matrixberegninger: 

(a) $A B$, 

(b) $A(B+C)$, 

(c) (CD) $A$, 

(d) $C(D A)$, 

(e) $(A(B D)) A$, 

(f) $(A B)(D A)$, 

(g) $A(B(D A))$.

In [1]:
import numpy as np
A = np.array([1000,70])
B = np.array([70,3000])
C = np.array([70,3000])
D = np.array([3000,1000])
CA = np.array([C[0],A[1]])
DA = np.array([D[0],A[1]])
BD = np.array([B[0],D[1]])
ABD = np.array([A[0],BD[1]])
AB = np.array([A[0],B[1]])
BDA = np.array([B[0],DA[1]])

def computeSizeOfMatrix(side):
    return eval(side)
    

def computeFlops(expression):
        exp = expression.split()
        op = exp[1]
        left = exp[0]
        right = "".join(exp[2:])
        match op:
            case "+":
                return computeSizeOfMatrix(left)[0] * computeSizeOfMatrix(left)[1] #matrix need to be same size
            
            case "-":
                return computeSizeOfMatrix(left)[0] * computeSizeOfMatrix(left)[1] #matrix need to be same size
                
            case "@":
                return 2*computeSizeOfMatrix(left)[0] * computeSizeOfMatrix(right)[0]* computeSizeOfMatrix(right)[1]
            

print("a",computeFlops("A @ B"))
print("b",computeFlops("A @ B") + computeFlops("B + C"))
print("c", computeFlops("C @ A") + computeFlops("A @ CA"))
print("d",computeFlops("D @ A") + computeFlops("C @ DA"))
print("e",computeFlops("B @ D") + computeFlops("BD @ A") + computeFlops("ABD @ A"))
print("f",computeFlops("A @ B") + computeFlops("D @ A") + computeFlops("AB @ DA"))
print("g",computeFlops("D @ A") + computeFlops("DA @ B") + computeFlops("A @ BDA"))

a 420000000
b 420210000
c 19600000
d 449400000
e 569800000
f 1260000000
g 1689800000


# Opgave 4.2.
Lad a være en ndarray (dvs. noget man får fra np . array) med to akser. Forklar hvad de følgende operationer gør ved a:

(a) $\mathrm{a}[2,[1,3,4,6]]=1$

sætter indangeende 1,3,4,6 i 2 række til at være en (Hvor man starter fra 0 række)

(b) $a[[1,2],[4,6]]=$ np.array $([5,7])$

Sætter indgang 1,4 til 5 og indgang 2,6 til 7

(c) $a[:,[3,1]]=a[:,[1,3]]$

Bytter rundt på søjlerne 1 og 3

(d) $a[2: 5,0]=$ np. $\operatorname{array}([0,1,2])$

sætter indgang 2,0 til 0 3,0 til 1 og 4,0 til 2

(e) $\mathrm{a}[4,3: 8: 2]+=6$

lægger 6 til i indgang 4,3 4,8 4,2

(f) a $[$ np.ix_( 1,2$],[4,6])]=n p . \operatorname{array}([[0,1],
[2,3]])$

lægger tallene ind fra højreside matricen in på de respektive koordinate fra venstresiden


Hvad er ulempen ved at skrive $a[2][3]$ i stedet for $a[2,3]$ ?
Man kan ikke se forskel på om a er en matrice eller en liste af lister


In [2]:
a = np.ones((10,10))
a[[1,2],[4,6]]= np.array([5,7])
print(a)
print()
a[:,3] = 2
a[:,1] = 9
print(a)
print()
a[:,[3,1]]=a[:,[1,3]]
print(a)
print()
a[2:5,0] = np.array([0,1,2])
print(a)
print()
a[4,3:8:2] += 6
print(a)
print()
a*=10
a[np.ix_( [1,2],[4,6])]=np.array([[0,1],[2,3]])
print(a)
print()

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 5. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 7. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 9. 1. 2. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 2. 5. 1. 1. 1. 1. 1.]
 [1. 9. 1. 2. 1. 1. 7. 1. 1. 1.]
 [1. 9. 1. 2. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 2. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 2. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 2. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 2. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 2. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 2. 1. 1. 1. 1. 1. 1.]]

[[1. 2. 1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 9. 5. 1. 1. 1. 1. 1.]
 [1. 2. 1. 9. 1. 1. 7. 1. 1. 1.]
 [1. 2. 1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 2. 1. 9. 1. 1. 1. 1. 1. 1.]]

[[1.

# Opgave 4.3.
Brug elementære rækkeoperationer til at bestemme alle løsninger til hver af de følgende lineære ligningssystemer:

(a) $\left\{\begin{aligned} 2 x-3 y & =7, \\ x+2 y & =-2 .\end{aligned}\right.$

(b) $\left\{\begin{aligned} 2 x+y-2 z & =1, \\ x-2 y+z & =-1, \\ 2 x+4 y+2 z & =0 .\end{aligned}\right.$

(c) $\left\{\begin{aligned} 2 x-y+2 z & =0, \\ x+y-z & =3 .\end{aligned}\right.$

Ved hjælp af dit svar for (b), afgør om der findes $a, b, c \in \mathbb{R}$ således at
$$
a\left[\begin{array}{l}
2 \\
1 \\
2
\end{array}\right]+b\left[\begin{array}{c}
1 \\
-2 \\
4
\end{array}\right]+c\left[\begin{array}{c}
-2 \\
1 \\
2
\end{array}\right]=\left[\begin{array}{c}
-1 \\
1 \\
0
\end{array}\right]
$$

## a)
$$
\begin{align}
2x-3y=7\\
x+2y=-2\\
\textit{2*r2}\\
2x+4y=-4\\
\textit{r2-r1}\\
7y=-11\\
y=-11/7
\end{align}
$$

sætter y's værdi in på dets plads
$$
\begin{align}
2x-3*(-11/7)=7\\
2x-(-33/7) = 7\\
2x = 7 -(33/7)\\
2x = 16/7\\
x = 8/7
\end{align}
$$

## b)

$$
\begin{align}
&2x+y-2z = 1\\
&x-2y+z=-1\\
&2x+4y+2z = 0\\
&\textit{R3-2R2}\\
&8y= 2\\
&y= 1/4\\
&\textit{indsætter y værdi}\\
&2x+1/4-2z = 1\\
&x-2/4+z=-1\\
&2x+1+2z = 0\\
&\textit{regner rundt}\\
&2x-2z = 3/4\\
&x+z=-0.5\\
&2x+2z = -1\\
&\textit{egentlig er det de to ligninger}\\
&x-z = 3/8\\
&x+z=-0.5\\
&\textit{isolere x}\\
&x= 3/8 + z\\
&\textit{indsætter}\\
&2z+3/8 = -0.5\\
&2z = -7/8\\
&z = -7/16\\
&\textit{har nu den sidste ligning}\\
&x + -7/16 = -0.5\\
&x= -1/16\\
&\end{align}
$$



## c)

$$
\begin{align}
2x-y+2z = 0\\
x+y-z = 3\\
\end{align}
$$
Der er uendeligt mange løsninger

# Opgave 4.4
(a) I første omgang bliver gennemstromningen ved fire punkter mảlt til at være $a=10, b=8, c=5 \operatorname{og} d=6$ liter $\mathrm{i}$ minuttet $(1 / \mathrm{min})$.

(i) Vis at det tilhorende linezre ligningssystemer for $e, f, g, h$ har ingen losning.

(ii) Derefter justerer på værdien for $d$ sảledes at systemet fâr en løsning.

(iii) Forklar hvorfor losningen til systemet i dette tilfæelde er ikke entydigt.

(b) Bestem et sæt af fire målepunkter således at der er altid en entydig losning for de andre værdier.

(c) Kan man nøjes med tre mãlepunkter og stadig fâr en entydig lesning?



# a)

## i)

Vi har her ligningsystemerne:

$$
\begin{align}
h = a+f\\
g = h-b\\
e = g-d\\
f = e+c\\
\end{align}
$$
Eftersom vi kender værdierne for a,b,c og d har vi så:
$$
\begin{align}
h = 10+f\\
g = h-8\\
e = g-6\\
f = e+5\\
\end{align}
$$
Omformer den:
$$
\begin{align}
h = 10 + 5 + e\\
h = 10 + 5 + g - 6\\
h = 10 + 5 + h - 8 - 6\\
h = 1+h
\end{align}
$$
Dette er en contradiction og den kan derfor ikke løses.

## ii)
d = 7
$$
\begin{align}
h = 10 + 5 + e\\
h = 10 + 5 + g - 7\\
h = 10 + 5 + h - 8 - 7\\
h = h
\end{align}
$$

### iii )
Omformer systemet:
$$
\begin{align}
h = 10+f\\
g = h-8\\
e = g-7\\
f = e+5\\
\textit{omformer systemet}\\
h-f = 10\\
g-h =-8\\
e-g =-7\\
f-e = 5\\
\end{align}
$$
Derved får vi den udviddede matrice:
$$
\begin{bmatrix}
0 & -1 & 0& 1 & 10\\
0 & 0 & 1 & 1 & -8\\
1 & 0 & -1 & 0 & -7\\
-1 & 1 & 0 & 0 & 5\\
\end{bmatrix}
$$
Omdanner denne til echelonform:


In [4]:
import sympy as sy
a = np.array([[0,-1,0,1,10],
             [0,0,1,1,-8],
             [1,0,-1,0,-7],
             [-1,1,0,0,5]])

sy.Matrix(a).rref()

(Matrix([
 [1, 0, 0, 0, -15],
 [0, 1, 0, 0, -10],
 [0, 0, 1, 0,  -8],
 [0, 0, 0, 1,   0]]),
 (0, 1, 2, 3))

Den har lige mange pivotelementer som søjler og derved ikke nogle frie variabler.


# b

Ligningssystemet for alle punkter bliver:
$$
\begin{align}
a = a
b = h-g
c = c
d = g-e
e = g-d
f = c+e
g = h-b
h = a + f
\end{align}
$$
Udfra dette skal vi måle a og c. Vi måler desuden e og g. På denne måde har vi værdier der medføre at vi kender alle punkternes værdier, eller kan regne os frem til det med de kendte værdier.

# c 
Ikke muligt da vi så ikke kan identificere et ligningssystem.

# Opgave 4.5. 
(a)Lad $A=u v^T$ med $u=(1,-1,2) \operatorname{og} v=(1,2,-1,-2)$.

Hvor mange pivotelementer er der i echelonformen for $A$ Lad $A=u v^T$ med $u=(1,-1,2) \operatorname{og} v=(1,2,-1,-2)$. Hvor mange pivotelementer er der i echelonformen for $A$ ?

(b) Hvis $B=u v^T$ med $u \in \mathbb{R}^m \operatorname{og} v \in \mathbb{R}^n$ vilkårlige, hvor mange pivotelementer kan der vare i echelonformen for $B$ ?

Der kommer kun 1 pivot element. Generelt 

(c) For $C=u v^T+w x^T, u, w \in \mathbb{R}^3, v, x \in \mathbb{R}^4$, afgør hvor mange pivotelementer echelonformen af $C$ kan have. Giv betingelser på $u, v, w, x$, der sikre at der er præcis 2 pivotelementer.

u og w må ikke være ens og v x er forskellige.



In [ ]:
## a
u = np.array([1,-1,2])[:,np.newaxis]
v = np.array([1,2,-1,-2])[:,np.newaxis]
a =  u @ v.T
print(a)
def change(i,j):
    a[[i,j],:] = a[[j,i],:]
def factor(i,s):
    a[i,:] *= s
def add(i,j,s):
    a[i,:] += t*a[j,:]
def sub(i,j,t):
    a[i,:] -= t*a[j,:]

sub(1,0,-1)
sub(2,0,2)
print("\n",a)
print("Den har kun 1 pivotelement")