In [14]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sy

# Opgave 12.1.
Givet matricen
$$
A=\left[\begin{array}{ll}
7 & 1 \\
6 & 2
\end{array}\right],
$$
bestem dens egenværdier. Find en basis for $\mathbb{R}^2$ bestående af egenvektorer for $A$.





$$
\begin{bmatrix}
7 & 1\\
6 & 2
\end{bmatrix}
-
\lambda
\begin{bmatrix}
\lambda & 0\\
0 & \lambda
\end{bmatrix}
=
\begin{bmatrix}
7-\lambda & 1\\
6 & 2-\lambda
\end{bmatrix}
$$
Udfra proposition 21.2 har vi at $det(A-\lambda I_2)=0$ for alle egenværdier. Derved har vi:
$$
det(
\begin{bmatrix}
7-\lambda & 1\\
6 & 2-\lambda
\end{bmatrix})
=
(7-\lambda)(2-\lambda)-1\cdot6 =
\lambda^2 - 9\lambda + 14 - 6 =
\lambda^2 - 9\lambda + 8
$$
for at tjekke at 8 og 1 er egenværdier kan man:
$$
8^2 - 9*8 + 8= 0
$$
og
$$
1^2-9+8 = 0
$$
Alternativt i python:

In [2]:
a = np.array([[7,1],
              [6,2]])

e, b = np.linalg.eig(a)
print("Egenværdier:\n", e)
print("\n egenvektorer:\n",b)

Egenværdier:
 [8. 1.]

 egenvektorer:
 [[ 0.70710678 -0.16439899]
 [ 0.70710678  0.98639392]]


# Opgave 12.2.
Betragt den øvre triangulær matrix
$$
A=\left[\begin{array}{ccc}
6 & -3 & 2 \\
0 & 2 & 7 \\
0 & 0 & -1
\end{array}\right] .
$$

Vis at 6, 2 og -1 er egenværdier for $A$, og bestem tilhørende egenvektorer. Vis desuden at
$$
\left(A-6 I_3\right)\left(A-2 I_3\right)\left(A+I_3\right)=0_3 .
$$
^12.1

Gøre rede at for en generel øvre triangulær matrix er indgangene på diagonalen netop matricens egenværdier. Er sådan en matrix nødvendigvis diagonaliserbar? Opfylder den en ligning af typen (12.1)?

In [3]:
# Test med den er diagonaliserbar
A = np.array([[6, -3, 2],
              [0, 2, 7],
              [0, 0, -1]])

e,v = np.linalg.eig(A)
print(v)
Lamb = np.diag(e)
test = v @ Lamb @ np.linalg.inv(v)
print(test)

[[ 1.          0.6        -0.45182352]
 [ 0.          0.8        -0.81997603]
 [ 0.          0.          0.3514183 ]]
[[ 6. -3.  2.]
 [ 0.  2.  7.]
 [ 0.  0. -1.]]


Matricer hvor den første søjle er 0 ikke invertibel.

matricer hvor den "nedre venstre indre matrice" er nul er ikke invertibel.

Matricer hvor den nedderste række er nul er ikke invertibel.

Derved når egenværdien er lig med en værdi i diogonalen, er en af disse ting opfyldt og de er derfor egenværdier.

De er diagonoliserbare.

12.1 virker altid, grundet matrixmultiplikation

## Eksmempel på hvorfor determinaten ikke kan bruges til en matrice der ikke er 2x2


Her vil vi benytte os af eksempel 21.4. Derved vil vi tjekke at $(A-\lambda I_3) = 0$

$$
\begin{bmatrix}
6 & -3 & 2\\
0 & 2 & 7\\
0 & 0 & -1
\end{bmatrix}
-\lambda
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
= 
\begin{bmatrix}
6-\lambda & -3 & 2\\
0 & 2-\lambda & 7\\
0 & 0 & -1- \lambda
\end{bmatrix}
$$
$$
det(\begin{bmatrix}
6-\lambda & -3 & 2\\
0 & 2-\lambda & 7\\
0 & 0 & -1- \lambda
\end{bmatrix}) =
(6-\lambda)det(
\begin{bmatrix}
2-\lambda & 7\\
0 & -1-\lambda
\end{bmatrix})
- (-3)\cdot det(\begin{bmatrix}0 & 7\\ 0 & -1-\lambda\end{bmatrix})
+
2\cdot det(\begin{bmatrix}0 & 2-\lambda\\ 0 & 0\end{bmatrix})
=
$$

$$
= (6-\lambda)((2-\lambda)(-1-\lambda)) =
-\lambda^3 + 7\lambda^2 - 4\lambda -12
$$

In [4]:
def func(x):
    return -x^3 + 7*x^2 - 4*x -12

print("for 6",func(6))
print("\n for 2",func(2))
print("\n for -1",func(-1))

for 6 9

 for 2 1

 for -1 7


## Rigtig
Eftersom det ovenover fejlede vil jeg benytte mig af proposition 21.2

In [5]:
A = np.array([[6, -3, 2],
              [0, 2, 7],
              [0, 0, -1]])

l = 6
I3 = np.identity(3)
for6 = A-(l*I3)
print(for6)
print(np.linalg.inv(for6))



[[ 0. -3.  2.]
 [ 0. -4.  7.]
 [ 0.  0. -7.]]


LinAlgError: Singular matrix

In [ ]:
l2 = 2
I3 = np.identity(3)
for2 = A-(l2*I3)
print(for2)
print(np.linalg.inv(for2))

In [ ]:
l3 = -1
I3 = np.identity(3)
forneg1 = A-(l3*I3)
print(forneg1)
print(np.linalg.inv(forneg1))

In [ ]:
print(for6)
print(for2)
print(forneg1)
print("other thing:\n",for6@for2@forneg1)

# Opgave 12.3.
Lad $u=(1,2,4), v=(-1,2,1)$ og sæt $A=u v^T$.

(a) Bestem en basis for $N(A)$.

(b) Find 2 lineært uafhængige egenvektorer for $A$ med egenværdi 0.

(c) Vis at $u$ er egenvektor for $A$, og bestem dens egenværdi.

(d) $\operatorname{Er} A$ diagonaliserbar?

## a

In [70]:
u = np.array([1.0,2.0,4.0])[:,np.newaxis]
v = np.array([-1.0,2.0,1.0])[:,np.newaxis]

A = u@v.T
print("A = \n",A)



sy.Matrix(A).rref()

A = 
 [[-1.  2.  1.]
 [-2.  4.  2.]
 [-4.  8.  4.]]


(Matrix([
 [1, -2.0, -1.0],
 [0,    0,    0],
 [0,    0,    0]]),
 (0,))

Vi har echeolonformen:
$$
\begin{bmatrix}
1 & -2 & -1\\
0 & 0 & 0\\
0 & 0 & 0 \\
\end{bmatrix}
$$

Vi får derfor ligningen:
$$
x_0 -2x_1 -x_2 = 0
$$
Derved får vi:
$$
\begin{bmatrix}
x_0\\
x_1\\
x_2
\end{bmatrix}
=
\begin{bmatrix}
2x_1 + x_2\\
x_1\\
x_2
\end{bmatrix}
= x_1
\begin{bmatrix}
2\\
1\\
0
\end{bmatrix}
+
x_2
\begin{bmatrix}
1\\
0\\
1
\end{bmatrix}
$$
Derved har vi at N(A) = 
$$
\begin{bmatrix}
2\\
1\\
0
\end{bmatrix}
\&
\begin{bmatrix}
1\\
0\\
1
\end{bmatrix}
$$

In [ ]:
n1 = np.array([2.0,1.0,0.0])[:,np.newaxis]
n2 = np.array([1.0,0.0,1.0])[:,np.newaxis]
print(A@(10*n1 + 24 * n2))

## b

In [71]:
e, vector = np.linalg.eig(A)
print("egenværdier:\n",np.round(e,5),"\n egenvektorer:\n",np.round(vector,5))


egenværdier:
 [ 7.+0.j -0.+0.j -0.-0.j] 
 egenvektorer:
 [[-0.21822+0.j       0.55053+0.21524j  0.55053-0.21524j]
 [-0.43644+0.j      -0.11991+0.10762j -0.11991-0.10762j]
 [-0.87287+0.j       0.79034+0.j       0.79034-0.j     ]]


Egenvektoren for 7 og for 0 er lineær uafhængige udfra proposition 21.5

## c

In [72]:
v = np.array([-1.0,2.0,1.0])[:,np.newaxis]
A = u@v.T
u = np.array([1.0,2.0,4.0])[:,np.newaxis]

print(A@u)
print(7*u)

[[ 7.]
 [14.]
 [28.]]
[[ 7.]
 [14.]
 [28.]]


## D
proposition 21.6 og 21.7

In [73]:
print(A)
Lamb = np.diag(e)
print(np.round(vector@Lamb@np.linalg.inv(vector),10))


[[-1.  2.  1.]
 [-2.  4.  2.]
 [-4.  8.  4.]]
[[-1.+0.j  2.-0.j  1.+0.j]
 [-2.+0.j  4.-0.j  2.-0.j]
 [-4.-0.j  8.-0.j  4.+0.j]]


# Opgave 12.4.

(a) Betragt matricen
$$
A=\left[\begin{array}{cc}
-1 & 2 \\
2 & -1
\end{array}\right]
$$

Bestem egenværdierne for $A$ og en ortonormal basis af egenvektorer.

(b) Løs begyndelsesværdiproblemet
$$
\begin{aligned}
& y_0^{\prime}(t)=-y_0(t)+2 y_1(t), \\
& y_1^{\prime}(t)=2 y_0(t)-y_1(t), \\
& y_0(0)=3, \quad y_1(0)=1 .
\end{aligned}
$$

Plot løsningerne i python.

## a


In [20]:
A = np.array([[-1,2],[2,-1]])
e, v = np.linalg.eig(A)
print("egenværdier:,\n",e,"\n Egenvektorbasis:\n",v)


import numpy as np
# Benytter os af af Defination 8.11
#Opgave A
def ortogonalCollection(listOfVectors):
    for i in listOfVectors:
        for j in listOfVectors:
            if np.array_equal(i,j):
                continue
            prikprodukt = i.T @ j
            if np.round(prikprodukt,16) != 0:
                return False
    return True
#Write Vectors
v0 = v[:,0]
v1 = v[:,1]
collectionOfVectors = [v0,v1]
print(ortogonalCollection(collectionOfVectors))
#Lemma 8.15
result = np.array([1/np.linalg.norm(v0)*v0,1/np.linalg.norm(v1)*v1])
print(result)
print(ortogonalCollection(result))

egenværdier:,
 [ 1. -3.] 
 Egenvektorbasis:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
True
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
True


## b

Prøver at følge eksempel 22.4

$$det(\begin{bmatrix}-1-\lambda & 2\\ 2 & -1-\lambda\end{bmatrix}) = (-1-\lambda)(-1-\lambda)-4 = \lambda^2 + 2\lambda - 3$$

In [22]:
aboveEquation = [1,2,-3]
print(np.roots(aboveEquation))
def poly(x):
    return x**2 + 2*x + 1
    
#fig, ax = plt.subplots()
#x = np.linspace(-10,10)
#ax.plot(x,poly(x))

[-3.  1.]


For 
$\lambda = -3$
$$
\begin{bmatrix}
-1--3 & 2\\
2 & -1--3
\end{bmatrix}
=
\begin{bmatrix}
2 & 2\\
2 & 2
\end{bmatrix}
$$

In [75]:
Aneg3 = np.array([[2.0,2.0],[2.0,2.0]])
v = np.array([-1,1])[:,np.newaxis];
print(Aneg3@v)
print(0*v)
print(np.linalg.eig(Aneg3))

[[0.]
 [0.]]
[[0]
 [0]]
EigResult(eigenvalues=array([4.0000000e+00, 4.4408921e-16]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))


Derved er vektoren:
$$
\begin{bmatrix}
-1\\
1
\end{bmatrix}
$$
en egenvektor

For $\lambda = 1$:
$$
\begin{bmatrix}
-1 -1 & 2\\
2 & -1-1
\end{bmatrix}
=
\begin{bmatrix}
-2 & 2\\
2 & -2
\end{bmatrix}
$$

In [69]:
Afor1 = np.array([[-2,2],[2,-2]])
v = np.array([1,1])[:,np.newaxis];
print(Afor1@v)
print(0*v)
np.linalg.eig(Afor1)

[[0]
 [0]]
[[0]
 [0]]


EigResult(eigenvalues=array([ 4.4408921e-16, -4.0000000e+00]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))

Derved er denne vektor også en egenvektor:
$$
\begin{bmatrix}
1\\
1
\end{bmatrix}
$$

Derved har vi løsningerne:
$$
y(t)=C0\begin{bmatrix}1\\-1\end{bmatrix}e^{-3t}+C1\begin{bmatrix}1\\1\end{bmatrix}e^{t} = \begin{bmatrix}3\\1\end{bmatrix}
$$

for t = 0 har vi så:
$$
y(t)=C0\begin{bmatrix}1\\-1\end{bmatrix}+C1\begin{bmatrix}1\\1\end{bmatrix} = \begin{bmatrix}3\\1\end{bmatrix}
$$

# Opgave 12.5.
Lad $A$ være en ( $2 \times 2)$-matrix. Vis at det karakteristiske polynomium for $A$ er lige med
$$
p(\lambda)=\lambda^2-\operatorname{Tr}(A) \lambda+\operatorname{det}(A),
$$
hvor $\operatorname{Tr}(A)=a_{00}+a_{11}$ er sporet af $A$. Hvis $A$ er diagonaliserbar, vis at egenværdierne $\lambda_0, \lambda_1$ for $A$ opfylder
$$
\lambda_0+\lambda_1=\operatorname{Tr}(A), \quad \lambda_0 \lambda_1=\operatorname{det}(A) .
$$

Diskutér mulige generalisering til større matricer.